Programming languages - "Lua" Complete Resources
jfmartinz/ResourceHub pull request #1005
Opened 2024-06-09 11:36 UTC by aditya-bhaumik

# Pull Request

## Description
@jfmartinz I have added the resources for Lua programming language please review and merge this pull request  

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2024-06-09 12:10 UTC, jfmartinz commented
Issue number

2024-06-09 12:37 UTC, aditya-bhaumik commented
Fixes #1007

2024-06-09 12:38 UTC, aditya-bhaumik commented
@jfmartinz please review and merge this pull request

2024-06-09 16:50 UTC, aditya-bhaumik commented
> #1007

2024-06-10 05:26 UTC, jfmartinz requested changes
Add the URLs into 'Resource Name'. Remove the third col

2024-06-10 05:26 UTC, jfmartinz commented on Programming Languages/lua/README.md
> +    <th>Link</th>
```suggestion

```

2024-06-10 05:26 UTC, jfmartinz commented on Programming Languages/lua/README.md
> +    <td><a href="https://opensource.com/article/20/12/lua-guess-number-game">Guess a number game</a></td>
```suggestion

```

2024-06-10 05:26 UTC, jfmartinz commented on Programming Languages/lua/README.md
> +    <td><a href="https://www.angrybirds.com">Pong game</a></td>
```suggestion

```

2024-06-10 07:03 UTC, aditya-bhaumik commented
@jfmartinz i have made the changes requested please merge my pull request

2024-06-10 14:10 UTC, aditya-bhaumik commented
@jfmartinz please merge this pull request under gssoc'24

2024-06-12 01:26 UTC, jfmartinz requested changes
The URL should be included in the name of the resource, same thing you did in the  web resources, remove the third col
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/ee9fbb42-23ee-412d-a18a-64aa3effed61)

2024-06-12 09:27 UTC, aditya-bhaumik commented
I already  made the changes  

![image](https://github.com/jfmartinz/ResourceHub/assets/92214013/8af1f5d7-259d-447c-b492-847b845065a0)

2024-06-13 06:35 UTC, jfmartinz approved these changes
LGTM

2024-06-13 06:35 UTC, merged