Programming Languages - "Lisp" Complete Resources
jfmartinz/ResourceHub pull request #1034
Opened 2024-06-10 08:09 UTC by kosuri-indu

## Description

Hii @jfmartinz
I have added Lisp resources in programming languages directory.
![image](https://github.com/jfmartinz/ResourceHub/assets/118645569/913bcb86-d73e-434a-8a4e-a2c0bfb939a6)

Closes #1027

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [x] Documentation enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

2024-06-10 08:11 UTC, kosuri-indu commented
@jfmartinz
Please review this PR :)
Thank you

2024-06-12 01:22 UTC, jfmartinz requested changes

2024-06-12 01:22 UTC, jfmartinz commented on Programming Languages/Lisp/readme.md
> +<th>Channel Name</th>
```suggestion
<th>Resource Name</th>
```

2024-06-13 01:43 UTC, kosuri-indu commented
@jfmartinz 
I have the respective changes sir

2024-06-13 06:45 UTC, jfmartinz approved these changes

2024-06-13 06:45 UTC, merged