UI/UX - Interview Preparation
jfmartinz/ResourceHub pull request #105
Opened 2023-10-23 12:46 UTC by karthxk07

### Fixes Issue
#104 

### Description:
Added Resources in the Interview preparation in UI/UX Category.

### Checklist:

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2023-10-23 12:48 UTC, karthxk07 commented
@jfmartinz are the resources fine

2023-10-23 12:57 UTC, jfmartinz requested changes

2023-10-23 12:57 UTC, jfmartinz commented on UI-UX Design/README.md
> +      <td>A platform that offers anonymous technical interview practice with experienced engineers from top tech companies.</td>
These resources are not related for the category UI & UX design.  You can check this [resource](https://www.youtube.com/playlist?list=PL1wFSWLYg_Ia97VL4pv-Ovz9330HfZX_k) currently in the interview section

2023-10-23 22:34 UTC, jfmartinz commented on UI-UX Design/README.md
> +      <td><a href="https://github.com/h5bp/Front-end-Developer-Interview-Questions">Front-end Developer Interview Questions</a></td>
I am sorry bro. I didnt see that this one is allso not accepted as a resource. Make sure it is related to UI UX design

2023-10-23 22:34 UTC, jfmartinz commented on UI-UX Design/README.md
> +      <td><a href="https://github.com/h5bp/Front-end-Developer-Interview-Questions">Front-end Developer Interview Questions</a></td>
Add something related to UUI UX design and I will merged it Once you completed it thanks

2023-10-25 03:07 UTC, jfmartinz commented
Something like [this](https://www.youtube.com/watch?v=2OzTi0iUMlE) if you have trouble finding one

2023-10-25 08:38 UTC, karthxk07 commented
Could i add this only , if it is ok?

2023-10-25 09:52 UTC, karthxk07 commented
@jfmartinz I have made the changes accordingly, could you please check and mege. :relaxed:

2023-10-25 10:03 UTC, jfmartinz approved these changes
Looks good! Thanks @karthxk07

2023-10-25 10:03 UTC, merged