Next js - Complete resources
jfmartinz/ResourceHub pull request #1086
Opened 2024-06-12 04:22 UTC by chaanakyaaM

# Pull Request

## Description
Please include a summary of the changes and the related issue.  

I have added next js complete resources under programming languages category
Closes # 463

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [x] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

## Additional

2024-06-12 04:23 UTC, chaanakyaaM commented
Kindly let me know if there are any changes to be made.

2024-06-13 06:39 UTC, jfmartinz requested changes

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +    <th>Resource</th>
```suggestion
    <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +    <th>Resource</th>
```suggestion
    <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +    <th>Resource</th>
```suggestion
    <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +    <th>Resource</th>
```suggestion
    <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +    <th>Resource</th>
```suggestion
    <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +    <th>Resource</th>
```suggestion
    <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 06:39 UTC, jfmartinz commented on Programming Languages/Next JS/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-13 08:22 UTC, chaanakyaaM commented
Done

2024-06-14 04:59 UTC, jfmartinz approved these changes

2024-06-14 04:59 UTC, merged