Interview section-- Interview Questions & articles
jfmartinz/ResourceHub pull request #111
Opened 2023-10-28 03:54 UTC by Chandan-Kumar-Mahato

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue
Closes #109 

### Description: 
Here i have added the interview section which includes videos and articles to read

### Resource URL: 

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2023-10-28 03:55 UTC, Chandan-Kumar-Mahato commented
Added the interview section .

2023-10-28 09:49 UTC, jfmartinz requested changes

2023-10-28 09:49 UTC, jfmartinz commented on Web Development/README.md
> +      <td>This is the collection of 10 articles in medium where you can learn and get engaged in the concept of web Development , this collection consists of learning of 10 years of a developer.</td>
Just remove this and I will merged this pr now. Thanks

2023-10-29 04:16 UTC, jfmartinz approved these changes
Thanks! Looks good :)

2023-10-29 04:17 UTC, merged