Programming languages - "Racket" Complete Resources
jfmartinz/ResourceHub pull request #1157
Opened 2024-06-14 17:36 UTC by aditya-bhaumik

# Pull Request

## Description
@jfmartinz I have added the complete resources for Racket programming language please review and merge this pull request

Closes #1155  

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2024-06-15 06:17 UTC, jfmartinz requested changes

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +Racket roadmap outlines the essential steps and skills needed to become proficient in Racket programming.
```suggestion
> Racket roadmap outlines the essential steps and skills needed to become proficient in Racket programming.
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +Introduction
```suggestion
> Offers step-by-step guides and tutorials covering various aspects of Racket programming. Helps beginners understand fundamental concepts and advanced users explore new techniques.
Introduction
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Racket 🎨
```suggestion
# Racket 
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Basics
```suggestion
### Basics
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Functions
```suggestion
### Functions
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Data Structures
```suggestion
### Data Structures
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Macros
```suggestion
### Macros
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Concurrency
```suggestion
### Concurrency
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Modules and Libraries
```suggestion
### Modules and Libraries
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Error Handling
```suggestion
### Error Handling
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## File I/O and Networking
```suggestion
### File I/O and Networking
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Web Development
```suggestion
### Web Development
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +Here are courses you may consider:
```suggestion
> Here are courses you may consider:
```

2024-06-15 06:17 UTC, jfmartinz commented on Programming Languages/Racket/README.md
> +## Resources
```suggestion
## Resources
```

Add the description

2024-06-15 08:35 UTC, aditya-bhaumik commented
@jfmartinz i made the changes requested please review and merge this pull request

2024-06-16 02:58 UTC, jfmartinz commented
You forgot Module Libraries. Make it h3

2024-06-16 03:46 UTC, aditya-bhaumik commented
@jfmartinz done

2024-06-17 06:03 UTC, jfmartinz approved these changes

2024-06-17 06:03 UTC, merged

2024-06-17 06:04 UTC, aditya-bhaumik commented
@jfmartinz please add the level label