assembly Language complete Resources.
jfmartinz/ResourceHub pull request #1195
Opened 2024-06-15 08:02 UTC by jayraj175coder

# Pull Request
I add assembly language resources..

## Description
Please include a summary of the changes and the related issue.  

Closes #923 

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [ ] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

![image](https://github.com/jfmartinz/ResourceHub/assets/135996214/276b2e2d-32f8-4e26-a77e-a9ce57de008e)

2024-06-16 02:57 UTC, jfmartinz requested changes

2024-06-16 02:57 UTC, jfmartinz commented on Programming Languages/Assembly/readme.md
> +Efficiency: Code written in assembly language can be highly optimized for performance and efficiency.
```suggestion

```

2024-06-16 02:57 UTC, jfmartinz commented on Programming Languages/Assembly/readme.md
> +   <th>Channel Name</th>
```suggestion
   <th>Resource Name</th>
```

2024-06-16 02:57 UTC, jfmartinz commented on Programming Languages/Assembly/readme.md
> +   <th>Playlist Name</th>
```suggestion
   <th>Resource Name</th>
```

2024-06-16 03:47 UTC, jayraj175coder commented
Done.

2024-06-17 06:03 UTC, jfmartinz approved these changes
LGTM

2024-06-17 06:03 UTC, merged