added cheatsheets section in DSA
jfmartinz/ResourceHub pull request #1198
Opened 2024-06-15 10:07 UTC by AmruthaPariprolu

# Pull Request

## Description
Please include a summary of the changes and the related issue.  

Closes # 

## Type of change
- [X ] Adding a new Resource
- [X ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [ X] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

## Additional

2024-06-16 03:00 UTC, jfmartinz requested changes

2024-06-16 03:00 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +### cheat-sheets
```suggestion
### Cheatsheet
```

2024-06-16 03:00 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +- [CheatSheets](#cheat-sheets)
```suggestion
- [Cheatsheet](#cheatsheet)
```

2024-06-16 03:47 UTC, AmruthaPariprolu commented
I have made the desired changes.Please do check..

2024-06-17 06:03 UTC, jfmartinz approved these changes

2024-06-17 06:03 UTC, merged