Added Computer Graphics Resource
jfmartinz/ResourceHub pull request #1338
Opened 2024-06-19 13:17 UTC by SadafKausar2025

# Pull Request  #1225 

## Description
Please include a summary of the changes and the related issue.  

Closes #1225 

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

## Additional

2024-06-19 13:17 UTC, SadafKausar2025 commented
hello @jfmartinz 
can you please review this PR?

2024-06-21 02:01 UTC, jfmartinz requested changes
You also remove the readme for this category
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/47ea633c-f9c3-483f-b753-f3e25ee5cb64)

2024-06-21 02:01 UTC, jfmartinz commented on Computer Graphics/readme.md
> +| [Real-Time Rendering Community](http://realtimerendering.com/) | The Real-Time Rendering Community offers resources and discussions on real-time rendering techniques, tools, and technologies.
Please take a look at these format. You should use the 'table' tags.

2024-06-21 04:51 UTC, SadafKausar2025 commented
> You also remove the readme for this category ![image](https://private-user-images.githubusercontent.com/129386460/341613126-47ea633c-f9c3-483f-b753-f3e25ee5cb64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDU3MTUsIm5iZiI6MTcxODk0NTQxNSwicGF0aCI6Ii8xMjkzODY0NjAvMzQxNjEzMTI2LTQ3ZWE2MzNjLWY5YzMtNDgzZi1iNzUzLWYzZTI1ZWU1Y2I2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNDUwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGRlNmRjNDg1YTZiZDQwYzFmNjgyNzQwMDgyMDhkMTZmNmJmMmQ5YmM3N2E3MDkzZDdlODcwNDg5M2QxMTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tlR0gsD0tqLercTG4_cBS4a6_Ey4NqfBcfX9oomCerw)

yes this was previously done by me . and you said anyone else is doing this so , I removed it

2024-06-21 05:16 UTC, SadafKausar2025 commented
hello @jfmartinz 
please see is this alright?
the NoSql code was of mine and you said that anyone else is doing work so I removed it

2024-06-21 20:40 UTC, jfmartinz commented
> hello @jfmartinz please see is this alright? the NoSql code was of mine and you said that anyone else is doing work so I removed it

My bad. Yes removed it.

2024-06-21 20:43 UTC, jfmartinz requested changes
Once these request changes is resolved, ill merged it. Thanks

2024-06-21 20:43 UTC, jfmartinz commented on Computer Graphics/readme.md
> +- [Tutorials or Courses](#tutorials-or-courses)<br>
```suggestion
- [Courses](#courses)<br>
```

2024-06-21 20:43 UTC, jfmartinz commented on Computer Graphics/readme.md
> +## Tutorials or Courses
```suggestion
## Courses
```

2024-06-21 20:43 UTC, jfmartinz commented on Computer Graphics/readme.md
> +</table>
```suggestion

```

2024-06-21 23:36 UTC, SadafKausar2025 commented
hello @jfmartinz 
please review the changes.
Is it alright?

2024-06-23 01:48 UTC, SadafKausar2025 commented
Hello @jfmartinz 
Please merge my pr

2024-06-23 06:12 UTC, jfmartinz approved these changes

2024-06-23 06:12 UTC, merged