📃 [ENHANCEMENT] -want to update Competitive programming documentation #1323
jfmartinz/ResourceHub pull request #1392
Opened 2024-06-21 20:30 UTC by nishant0708

#1323 

## Description
Added How to start Competitive programing and added more resources 

Closes # 

## Type of change
- [y ] Adding a new Resource
- [y ] Adding a new Category
- [ y] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [ y] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [y ] I have performed a self-review of my own code
- [y ] I have commented my code, particularly in hard-to-understand areas
- [ y] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

## Additional

2024-06-21 21:02 UTC, jfmartinz requested changes

2024-06-21 21:02 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/Competitive Programming/readme.md
> +7. **Stay Inspired**: Follow competitive programming champions and watch their problem-solving techniques.
```suggestion

```

2024-06-21 21:08 UTC, nishant0708 commented on Data Structures and Algorithm (DSA)/Competitive Programming/readme.md
> +7. **Stay Inspired**: Follow competitive programming champions and watch their problem-solving techniques.
Hey @jfmartinz should i remove it ??

2024-06-21 21:09 UTC, nishant0708 commented
hey @jfmartinz now check it

2024-06-23 05:25 UTC, jfmartinz approved these changes

2024-06-23 05:25 UTC, merged