Web development - Web Design for Everybody: Basics of Web Development & Coding Specialization   &   Front-End Development
jfmartinz/ResourceHub pull request #146
Opened 2024-05-11 15:02 UTC by BagchiShreya

Added a new front-end resource (Coursera course link)

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue #143 

### Description: This is a beginner friendly Coursera course about front-end development.

### Resource URL: https://www.coursera.org/specializations/web-design?skipBrowseRedirect=true

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-05-11 15:28 UTC, jfmartinz requested changes

2024-05-11 15:28 UTC, jfmartinz commented on Web Development/README.md
> +  <tr>
This is not suitable to the web development under tutorial or courses, instead you can put it in the [Category Section](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design) under [Tutorial or Courses](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design#tutorials-or-courses). After these change, I will merged your pr, thank you!

2024-05-11 15:29 UTC, jfmartinz requested changes

2024-05-11 15:29 UTC, jfmartinz commented on Web Development/README.md
> +    <td><a href="https://www.coursera.org/specializations/web-design?skipBrowseRedirect=true">Web Design for Everybody: Basics of Web Development & Coding Specialization]</a></td>
This is not suitable to the web development under tutorial or courses, instead you can put it in the [Category Section](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design) under [Tutorial or Courses](https://github.com/jfmartinz/ResourceHub/tree/main/UI-UX%20Design#tutorials-or-courses). After these change, I will merged your pr, thank you!

2024-05-12 02:22 UTC, jfmartinz approved these changes
Looks good

2024-05-12 02:25 UTC, jfmartinz commented
One more thing @BagchiShreya before I merged this PR, you need to resolve the conflict, you can check this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) for more information

2024-05-12 04:52 UTC, BagchiShreya commented
> One more thing @BagchiShreya before I merged this PR, you need to resolve the conflict, you can check this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) for more information

I resolved the conflict

2024-05-12 05:10 UTC, merged