DBMS - Tutorial or courses
jfmartinz/ResourceHub pull request #312
Opened 2024-05-19 05:29 UTC by sau-mili

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue

fixes #294 

### Description: 

Added two resources of DBMS tutorials or courses

### Resource URL: 

https://www.youtube.com/watch?v=ExcRbA7fy_A&list=PL4cUxeGkcC9h77dJ-QJlwGlZlTd4ecZOA&ab_channel=NetNinja
https://www.udemy.com/course/database-engines-crash-course/?couponCode=LEADERSALE24A

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-05-19 06:34 UTC, jfmartinz requested changes

2024-05-19 06:34 UTC, jfmartinz commented on DBMS (Database)/README.md
> +      <td><a href="https://shorturl.at/6oNur">NetNinja Youtube</a></td>
Thhe URL is 404, not found.

2024-05-19 06:38 UTC, sau-mili commented
Can you check now?

2024-05-19 06:52 UTC, jfmartinz approved these changes
Looks good @sau-mili

2024-05-19 06:53 UTC, jfmartinz commented
Wait you need to resolve the conflict, this link might help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

2024-05-19 06:56 UTC, sau-mili commented
But, in this pull req, it says I can't resolve it because I Dont have writing access
![Screenshot 2024-05-19 122621](https://github.com/jfmartinz/ResourceHub/assets/146661411/be3f75d1-0ce0-4b13-8baf-c8458464a0c3)

2024-05-19 17:17 UTC, sau-mili commented
@jfmartinz please check this. I have raised more issues

2024-05-20 05:33 UTC, jfmartinz commented
Resolve Conflict first, thnaks

2024-05-20 05:36 UTC, sau-mili commented
Please check the screenshot, resolve button is greyed out for me

2024-05-20 05:37 UTC, sau-mili commented
Should I close the pull and redo it altogether?

2024-05-20 05:46 UTC, closed without merging

2024-05-20 05:49 UTC, jfmartinz commented
I cant merged it because there is conflict on the changes you made. I sent you a link, what it is already, you can read it. Its grey means that you need to resolve first before that PR be able to merged into main. 

yes you can redo it instead. Just dont forget to pull before create changes so that eveything is up to date and prevent conflict, thanks

2024-05-20 05:53 UTC, sau-mili commented
#343 redo done