Open Source Development - Bitbucket
jfmartinz/ResourceHub pull request #327
Opened 2024-05-19 13:43 UTC by PradnyaGaitonde

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Closes Issue
> KEYWORD #ISSUE-NUMBER. For example: Closes #10 
closes #262 

### Description: 
> Provide a brief description of the pull request
added resource for open-source development

### Resource URL: 
> Insert the URL of the resource you're proposing 
https://bitbucket.org/

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

2024-05-23 08:17 UTC, jfmartinz requested changes
The Bitbucket link is not working because of this

2024-05-23 08:17 UTC, jfmartinz commented on Open Source Development/readme.md
> +  </tr>
```suggestion
  <tr>
    <td><a href="https://bitbucket.org/">Bitbucket</a></td>
    <td>What is BitBucket and How it works? An Overview and Its Use ...Bitbucket is a cloud-based Git-based service that allows developers to store, manage, and track code changes. It's designed for professional teams, providing a central place to collaborate on source code, plan projects, and test and deploy code.</td>
  </tr>
```

2024-05-23 13:23 UTC, PradnyaGaitonde commented on Open Source Development/readme.md
> +  </tr>
Carried out the changes.

2024-05-24 04:44 UTC, jfmartinz approved these changes
Thanks

2024-05-24 04:45 UTC, merged