Python Development resources added
jfmartinz/ResourceHub pull request #357
Opened 2024-05-21 06:12 UTC by Pujan-sarkar

PR Title:

`Python Development - New Domain Added`

### Closes Issue
> Fixes #291 

### Description: 
> I have added the full resources of Python Development .

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-05-21 14:24 UTC, jfmartinz requested changes
Add this folder inside [this](https://github.com/jfmartinz/ResourceHub/tree/main/Programming%20Languages/Java) folder. Rename it to Just Python maybe, and use format like readme.md

2024-05-21 15:27 UTC, Pujan-sarkar commented
@jfmartinz can i rename the readme file in python.md

2024-05-21 16:30 UTC, Pujan-sarkar commented
@jfmartinz i have done it can you check please

2024-05-22 03:29 UTC, jfmartinz approved these changes

2024-05-22 03:30 UTC, merged