Update README.md with examples of Full Stack Technologies #198
jfmartinz/ResourceHub pull request #412
Opened 2024-05-23 11:31 UTC by dadigavasavipriya

This pull request introduces comprehensive resource lists for various technology stacks used in web development. These stacks include LAMP, MEAN, Ruby on Rails, Python Django, Java, and ASP.NET. Each section contains curated links to tutorials, guides, and project ideas to help developers master full-stack development with these technologies.

Additions:

1.Introduction to Technology Stacks
Overview of full-stack development and the importance of mastering specific technology stacks.

2.Building Web Applications with LAMP Stack
Resources on Linux, Apache, MySQL, PHP.
Links to tutorials, roadmaps, and project examples.

3.Creating Web Apps with MEAN Stack
Resources on MongoDB, Express, Angular, Node.js.
Links to tutorials, roadmaps, and project examples.

4.Creating Web Applications with Ruby on Rails
Resources on Ruby, Rails, SQLite/MySQL/PostgreSQL, JavaScript.
Links to tutorials, roadmaps, and project examples.

5.Python Web Development using Django
Resources on Python, Django, React.js, MySQL.
Links to tutorials, roadmaps, and project examples.

6.Full-Stack Development with Java
Resources on Java, Spring Boot, React, MongoDB.
Links to tutorials, roadmaps, and project examples.

7.Developing Web Applications with ASP.NET
Resources on ASP.NET, C#, SQL Server.
Links to tutorials, roadmaps, and project examples.

8.Creating Web Apps with MERN Stack
Resources on MongoDB, Express, React, Node.js.
Links to tutorials, roadmaps, and project examples.

2024-05-24 05:16 UTC, jfmartinz requested changes
Also remove the description in each stacks in the table, only add description into the Technology Stacks and describe the content or about the resources included. Thanks

2024-05-24 05:16 UTC, jfmartinz commented on Web Development/readme.md
> +- [Full-stack with various technology stacks](#various-technolgy-stacks)
```suggestion
- [Technology Stacks](#technolgy-stacks)
```

2024-05-24 05:16 UTC, jfmartinz commented on Web Development/readme.md
> +### Various Technolgy Stacks
```suggestion
### Technology Stacks
```

2024-05-26 04:19 UTC, jfmartinz approved these changes
Please remove these descriptions:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/f4c86fb0-bfd4-4457-99da-d380b423f774)
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/815bdcbc-068c-480d-9e58-0fd35e092dd4)

All the descriptions you added in the table. Only technology stacks should have a description, other tables below, please remove.


Another one is, please add those stacks in the table of contents, the same thing with what you see in the Projects section:

![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/e2057f52-b7f3-4901-ac32-806a47ce1143)

2024-05-26 04:51 UTC, jfmartinz approved these changes
Thanks @dadigavasavipriya

2024-05-26 04:51 UTC, merged

2024-05-26 04:51 UTC, dadigavasavipriya commented
@jfmartinz Thank you for your feedback. I have removed the descriptions from the tables as requested, except for the Technology Stacks Additionally, I have added the Technology Stacks section to the table of contents, following the same format as the Projects section.
Thank you once again for assigning me this issue. Please let me know if there are any further adjustments needed.

2024-05-26 04:54 UTC, jfmartinz commented
Merged your PR, thansk for your contribution

2024-05-26 04:56 UTC, dadigavasavipriya commented
You're welcome, @jfmartinz! If there is any further changes required, please let me know.I'm glad to contribute to the project.