Programming Languages - Python Project section
jfmartinz/ResourceHub pull request #446
Opened 2024-05-24 16:18 UTC by Varsha010101

Programming Languages - Python Project section

### Description: 
This pull request adds python projects to build up a resume. It has projects at beginner, intermediate and advanced level. It provides all resources including source code, documentation and tutorials 

### Resource URL: 
>These are only some of the URLS to the source code I have provided in the python project section:
-https://github.com/topics/python-blockchain
-https://pythongeeks.org/python-library-management-system-project/
-https://www.geeksforgeeks.org/real-time-translation-app-using-python/
-https://www.geeksforgeeks.org/gui-chat-application-using-tkinter-in-python/
-https://realpython.com/build-a-chatbot-python-chatterbot/
-https://www.geeksforgeeks.org/data-visualization-with-python/
-https://pythongeeks.org/python-music-player/
-https://cointrader.readthedocs.io/en/latest/_modules/cointrader/chart.html

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-05-24 16:24 UTC, Varsha010101 commented
@jfmartinz Kindly label this PR under GSSoC.

2024-05-25 01:41 UTC, jfmartinz requested changes

2024-05-25 01:41 UTC, jfmartinz commented on Programming Languages/Python/readme.md
> +    <th>Resources</th>
The order of the col should be:
1. Resource Name
2. Description

Remove the Project Name and add the URL into the Resource Name

for example:

```html
<td><a href="URL">Resource Name </a> </td>
```

2024-05-25 06:29 UTC, Varsha010101 commented
Yes, I have made the requested changes kindly review it. @jfmartinz

2024-05-25 08:17 UTC, jfmartinz requested changes
The heading is too small:

![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/c83b2907-46c9-486e-88f9-b7c6fc5e5d10)

2024-05-25 08:32 UTC, jfmartinz requested changes

2024-05-25 08:32 UTC, jfmartinz commented on Programming Languages/Python/readme.md
> +#### Python Projects
```suggestion
### Python Projects
```

2024-05-25 08:39 UTC, jfmartinz commented
Still small. Can you check at your end?

2024-05-25 12:32 UTC, jfmartinz requested changes

2024-05-25 12:32 UTC, jfmartinz commented on Programming Languages/Python/readme.md
> +# Python Projects
```suggestion
### Python Projects
```

2024-05-26 10:08 UTC, jfmartinz approved these changes
Thanks @Varsha010101

2024-05-26 10:09 UTC, jfmartinz commented
Can you please solve the conflict

2024-05-27 06:09 UTC, jfmartinz requested changes

2024-05-27 06:09 UTC, jfmartinz commented on Programming Languages/Python/readme.md
> +  <tr>https://github.com/jfmartinz/ResourceHub/pull/446/conflict?name=Programming%2BLanguages%252FPython%252Freadme.md&ancestor_oid=ce12fab1fd551f6f14b3dd9b47e739d674220cb2&base_oid=a312ecd67ff407e8d
```suggestion
  <tr>
```

2024-05-28 02:30 UTC, jfmartinz requested changes
Check Java file:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/5afc5d8a-483b-448b-b4cf-c3a6f53f904d)

Please remove it.

In Python, you remove:

![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/090c2229-cc14-46c2-9d41-2ccd7206fa9d)

In Youtube Playlist

2024-05-28 02:30 UTC, jfmartinz commented on Programming Languages/Python/readme.md
> +
```suggestion
```

2024-05-28 08:14 UTC, jfmartinz requested changes

2024-05-28 08:14 UTC, jfmartinz commented on Programming Languages/Python/readme.md
> +
```suggestion
### YouTube Playlists
```

2024-05-28 08:14 UTC, jfmartinz commented on Programming Languages/Python/readme.md
>  =======
```suggestion

```

2024-05-28 09:18 UTC, Varsha010101 commented
The changes mentioned are already done. Could you please tell if any other changes required.

2024-05-30 13:10 UTC, jfmartinz commented
Can please raise another PR, the PR is already messy and there is a conflict.

2024-05-30 14:31 UTC, closed without merging