Added Github section in Devops resources
jfmartinz/ResourceHub pull request #473
Opened 2024-05-25 12:36 UTC by Pujan-sarkar

## - `DevOps- ` - GitHub Repository

Fixes #425 

### Description: 
> I have added GitHub repository links in the DevOps resources.

### Checklist: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-05-25 12:37 UTC, Pujan-sarkar commented
@jfmartinz  i have created new pr , check this time

2024-05-26 04:56 UTC, jfmartinz requested changes

2024-05-26 04:56 UTC, jfmartinz commented on DevOps/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>

```

2024-05-26 13:12 UTC, Pujan-sarkar commented
@jfmartinz  I CANT UNDERSTAND THE CHNAGES YOU WANT AND I HAVE ALREADY DONE IT , SO CAN YOU CHECK IT ONCE

2024-05-26 14:47 UTC, Pujan-sarkar commented
@jfmartinz  please can you reply..

2024-05-27 06:04 UTC, jfmartinz approved these changes
Thanks @Pujan-sarkar.

2024-05-27 06:04 UTC, merged

2024-05-27 06:05 UTC, jfmartinz commented
I hope you understand that I can quicly reply to the messages, I am the only one maining the project and also have school. 

> @jfmartinz please can you reply..

2024-05-27 06:05 UTC, jfmartinz commented
Also the PR is less than a day

2024-05-27 06:07 UTC, Pujan-sarkar commented
@jfmartinz sorry sir... For the disturbance

2024-05-27 06:11 UTC, jfmartinz commented
No worries 👍