Programming Languages - NodeJs Complete Resources
jfmartinz/ResourceHub pull request #492
Opened 2024-05-26 13:06 UTC by Santhosh-Siddhardha

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #442 

### Description: 
Hey @jfmartinz I have added the resources of NodeJs

```
 ./Programming Languages
    /NodeJs
     /readme.md
```
Please take a look, Thank you.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

2024-05-27 06:03 UTC, jfmartinz requested changes

2024-05-27 06:03 UTC, jfmartinz commented on Programming Languages/NodeJs/readme.md
> +These resources are designed to help you build a strong foundation in Node.js and apply it effectively to your server-side and real-time application development tasks. Whether you are a beginner star
```suggestion

```

please remove key features

2024-05-27 06:07 UTC, Santhosh-Siddhardha commented on Programming Languages/NodeJs/readme.md
> +These resources are designed to help you build a strong foundation in Node.js and apply it effectively to your server-side and real-time application development tasks. Whether you are a beginner star
Removed Key features

2024-05-27 11:04 UTC, Santhosh-Siddhardha commented
@jfmartinz Made changes, Have a look

2024-05-28 02:31 UTC, jfmartinz approved these changes
Thanks

2024-05-28 02:31 UTC, merged

2024-05-30 11:51 UTC, Santhosh-Siddhardha commented
@jfmartinz Please assign this PR to me.