Programming Languages - "AngularJs" Complete Resources
jfmartinz/ResourceHub pull request #536
Opened 2024-05-28 07:42 UTC by Santhosh-Siddhardha

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #456 

### Description: 
Hey @jfmartinz I have added the resources of AngularJs

```
 ./Programming Languages
    /AngularJs
     /readme.md
```
Please take a look, Thank you.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

2024-05-28 08:10 UTC, jfmartinz requested changes

2024-05-28 08:10 UTC, jfmartinz commented on Programming Languages/AngularJS/readme.md
> +   - [YouTube Channels to Learn AngularJS](#youtube-channels-to-learn-angularjs)
```suggestion
   - [YouTube Channels](#youtube-channels)
```

2024-05-28 08:39 UTC, Santhosh-Siddhardha commented
@jfmartinz Made changes, Have a look

2024-05-28 15:35 UTC, merged

2024-05-30 12:05 UTC, jfmartinz commented
No need. I think

2024-05-30 12:09 UTC, Santhosh-Siddhardha commented
@jfmartinz Today all the Contributors got a mail, and these important things were mentioned in that mail, Have a look

2024-05-30 12:10 UTC, jfmartinz commented
Only in 'Issue', I think no need in PR. You just need to reference the issue, let me confirm it

2024-05-30 12:17 UTC, Santhosh-Siddhardha commented
Once have a look in this , https://github.com/GSSoC24/Contributor/discussions/288?utm_source=substack&utm_medium=email

2024-05-30 12:21 UTC, jfmartinz commented
Okay, sure. THey announced too late again, ive merged alot prs already.

2024-05-30 12:24 UTC, jfmartinz commented
I will do that.

2024-05-30 12:27 UTC, Santhosh-Siddhardha commented
@jfmartinz thank you

2024-05-30 12:34 UTC, jfmartinz commented
Can you please not mentioned again, I will jusst assigned and add labels to the PRs merged. My notif is flooded right now, hope you understand. Just remind me if i forgot

2024-05-30 12:35 UTC, Santhosh-Siddhardha commented
Yeah sure.... I can understand

2024-06-28 03:03 UTC, sanjay-kv commented
@Santhosh-Siddhardha as per guidelines only 200 points are allowed. 
![image](https://github.com/jfmartinz/ResourceHub/assets/30715153/9083c5e4-0b46-4bfe-8edd-8125d7239ff3)