Programming Languages - Additional Resources for "TypeScript"
jfmartinz/ResourceHub pull request #627
Opened 2024-05-30 21:39 UTC by MastanSayyad

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

### Description: 
Hey @jfmartinz I have added some additional resources for Typescript such as
- Typescript Validation
- Additional TS Libraries
- Additional Books

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-05-31 14:51 UTC, jfmartinz requested changes

2024-05-31 14:51 UTC, jfmartinz commented on Programming Languages/TypeScript/readme.md
> +      <th>Library</th>
```suggestion
      <th>Resource Name</th>
```

For consistency, please rename it, thanks 👍

2024-05-31 17:23 UTC, MastanSayyad commented
Done @jfmartinz , I'll make sure it does not happen next time

2024-06-02 16:34 UTC, jfmartinz commented
> Done @jfmartinz , I'll make sure it does not happen next time

No worries @MastanSayyad

2024-06-02 16:34 UTC, jfmartinz approved these changes
Thanks

2024-06-02 16:35 UTC, merged