Programming Languages - Added Dart Complete Resources
jfmartinz/ResourceHub pull request #646
Opened 2024-05-31 12:44 UTC by Vaibhavsg17

- I have added the All Resources for DART Programming Languages 

Closes #500 

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

2024-05-31 14:36 UTC, jfmartinz requested changes

2024-05-31 14:36 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +- **Embedded Systems:** Flutter can also be used for developing embedded systems applications
```suggestion

```

2024-05-31 18:57 UTC, Vaibhavsg17 commented
@jfmartinz i have removed flutter part now check

2024-06-01 12:46 UTC, Vaibhavsg17 commented
@jfmartinz i have solved the issue now you can merge the pr

2024-06-02 16:29 UTC, jfmartinz requested changes

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +- [Community and Support](#community-and-support)
```suggestion
- [Community](#community)
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +### Tools and IDEs
```suggestion
### Tools
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +        <th>Tool/IDE Name</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +        <th>Book Title</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +        <th>Channel/Playlist</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +### Community and Support
```suggestion
### Community
```

2024-06-02 16:29 UTC, jfmartinz commented on Programming Languages/Dart/readme.md
> +        <th>Resource</th>
```suggestion
        <th>Resource Name</th>
```

2024-06-07 04:41 UTC, jfmartinz approved these changes

2024-06-07 04:41 UTC, merged