PROGRAMMING LANGUAGES- PYTHON-ADDED PYTHON PROJECTS SECTION
jfmartinz/ResourceHub pull request #770
Opened 2024-06-03 07:39 UTC by Varsha010101

### Description: 
It looks forward to cover projects in beginner, intermediate and advance level a user can show to build up his resume. It will cover project topics like:
Calculator
chatbot
machine learning model
banking system
and many more

### Resource URL: 
> Insert the URL of the resource you're proposing
- https://realpython.com/build-a-chatbot-python-chatterbot/
- https://www.geeksforgeeks.org/real-time-translation-app-using-python/
- https://github.com/topics/python-blockchain

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2024-06-03 07:44 UTC, Varsha010101 commented
Kindly review this PR and label it under GSSoC @jfmartinz. Refers to issue number #401

2024-06-03 13:08 UTC, jfmartinz requested changes
Another change is that you removed the Youtube Playlist and Conclusion:

![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/0faaf710-1c28-435f-88c6-3993aa588523)

Add your pyton projects before conclusion

2024-06-03 13:08 UTC, jfmartinz commented on Programming Languages/Java/readme.md
> +  <td>Coin Trader is a Java-based backend for algorithmically trading cryptocurrencies. It provides data collection and export, complex event processing and triggering, and backtesting - paper tradin
```suggestion

```

2024-06-04 14:57 UTC, Varsha010101 commented
@jfmartinz All mentioned changes have been updated. Please review this PR and merge it.

2024-06-05 15:07 UTC, Varsha010101 commented
@jfmartinz All mentioned changes have been updated. Please review this PR and merge it.

2024-07-29 16:50 UTC, closed without merging