Added the Gssoc banner
jfmartinz/ResourceHub pull request #802
Opened 2024-06-03 15:03 UTC by Maheshwari-Love

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #654 

### Description: 
I have added the GSSoC'24 banner in the README.md file

### Resource URL: 
> Insert the URL of the resource you're proposing
- 
-
-

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

2024-06-03 15:05 UTC, Maheshwari-Love commented
@jfmartinz please review and merge it

2024-06-05 05:45 UTC, jfmartinz requested changes
Add it also below technologies table of contents:

![Uploading image.png…]()

2024-06-05 05:45 UTC, jfmartinz commented on README.md
> +## GSSoC'24
```suggestion
## Organization
```

2024-06-05 05:45 UTC, jfmartinz commented on README.md
> +
```suggestion
ResourceHub is participating in GirlScript Summer of Code (GSSoC), an annual open-source program by the GirlScript Foundation. GSSoC promotes gender diversity and inclusion in tech by enabling participants to contribute to various projects under expert mentorship. We are excited to collaborate with talented individuals and advance our project through this initiative.
```

2024-06-06 12:26 UTC, jfmartinz requested changes
Add the link after the technologies:
![Uploading image.png…]()

2024-06-06 14:56 UTC, jfmartinz approved these changes

2024-06-06 14:56 UTC, merged