Web development - Typography , Colors , Icons , Stock Photos & Videos     fixes #81
jfmartinz/ResourceHub pull request #88
Opened 2023-10-17 10:10 UTC by rajvinder-kaur

### Fixes Issue
fixes #81

### Description: 
i added resources about colors,typography,icons and  Stock Photos & Videos

### Resource URL: 
typography****
https://fonts.google.com/
https://fonts.adobe.com/
https://fontsinuse.com/
https://www.typewolf.com/
https://typehunting.com/
https://typography-daily.com/
colors***
https://flatuicolors.com/
https://realtimecolors.com
https://color.adobe.com/create/color-wheel
https://paletton.com/
https://brandcolors.net/
https://colorkuler.com/
https://www.designspiration.com/
https://www.sherwin-williams.com/content/colorsnap
icons**
https://www.flaticon.com/
https://www.iconfinder.com/
https://thenounproject.com/
https://graphicburger.com/
https://mariodelvalle.github.io/CaptainIconWeb/
stock images and videos***
https://www.shutterstock.com/
https://unsplash.com/
https://www.pexels.com/
https://pixabay.com/
https://www.videezy.com/
https://mixkit.co/

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2023-10-17 10:43 UTC, jfmartinz requested changes

2023-10-17 10:43 UTC, jfmartinz commented on .vscode/settings.json
> +}
Please remove this one. Thanks

2023-10-17 10:44 UTC, jfmartinz commented
Also Solve the branch conflict.  If you don't know how to solve, you can go [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

2023-10-18 10:02 UTC, rajvinder-kaur commented on .vscode/settings.json
> +}
i removed the code

2023-10-18 10:03 UTC, rajvinder-kaur commented
i solved the conflicts please review it

2023-10-18 10:32 UTC, jfmartinz approved these changes
looks good! Thanks @rajvinder-kaur. ❤️

2023-10-18 10:32 UTC, merged

2023-10-25 15:40 UTC, rajvinder-kaur commented
can you please put a approved label on it. please it will help my pr to get selected for hactoberfest

2023-10-25 23:22 UTC, jfmartinz commented
Sure. Thanks @rajvinder-kaur

2023-10-25 23:30 UTC, jfmartinz commented
I am encouraging you to contribute more on the project by adding resources. Thanks