Lack resources in tools section for web development
jfmartinz/ResourceHub pull request #91
Opened 2023-10-18 02:56 UTC by Dev-Abhay01

**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue #81 

### Description: i have added resources about typography

### Resource URL: 
Fontjoy: https://fontjoy.com/
Typewolf: https://www.typewolf.com/

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ *] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ *] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

2023-10-18 02:56 UTC, Dev-Abhay01 commented
please review and merge it... @jfmartinz

2023-10-18 03:51 UTC, jfmartinz requested changes
Once you fixed these problemms, I will merged it. Thanks

2023-10-18 03:51 UTC, jfmartinz commented on Web Development/README.md
> +        <td><a href="https://www.typewolf.com/">Typewolf</a></td>
Please removed this one. Someone wants to add this resource already in the section

2023-10-18 03:51 UTC, jfmartinz commented on Web Development/README.md
> +    </tr>
Removed this resource also

2023-10-19 03:46 UTC, Dev-Abhay01 commented
Im just closing this pull request and raised it again please merge it then

2023-10-19 03:47 UTC, closed without merging