DSA implemations of several Programming languages
jfmartinz/ResourceHub pull request #930
Opened 2024-06-07 14:23 UTC by Pujan-sarkar

# Pull Request

## Description

This repository contains a collection of Data Structures and Algorithms (DSA) implementations across various programming languages. Each section is organized by language and includes common DSA topics such as arrays, strings, linked lists, trees, and more.  

Fixes #796 

## Type of change
- [X] Adding a new Resource
- [X] Adding a new Category
- [X] Documentation enhancement or fixes
- [X] Website enhancement or fixes

## Checklist:
- [X] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

2024-06-07 14:24 UTC, Pujan-sarkar commented
@jfmartinz  please check this pr and merge .

2024-06-08 03:37 UTC, Pujan-sarkar commented
@jfmartinz  please merge the pr please

2024-06-08 09:35 UTC, jfmartinz commented
You don't need to add new readme, just add it [here](https://github.com/jfmartinz/ResourceHub/tree/main/Data%20Structures%20and%20Algorithm%20(DSA))

Follow this format, each language should have their own table
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/3c93ae0b-84bc-49a0-a2e5-31a42ebe56c2)

2024-06-08 09:35 UTC, Pujan-sarkar commented
@jfmartinz I add a new folder please level 3 or level 2 .

2024-06-08 09:36 UTC, jfmartinz commented
Follow this format for adding a new table:

https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md

2024-06-08 09:37 UTC, jfmartinz commented
Add it into a table. Each programing language shoukld have a table each

2024-06-08 10:15 UTC, Pujan-sarkar commented
@jfmartinz okay tell me i have to add the dsa table in the three programming language's folder ?

2024-06-08 10:36 UTC, Pujan-sarkar commented
@jfmartinz I have to add the table of every DSA of every language in the DSA folder ?????

2024-06-08 18:10 UTC, Pujan-sarkar commented
@jfmartinz please check I have done the changes as you said earlier.

2024-06-09 02:54 UTC, jfmartinz requested changes
Follow this format for table:

### C++
<table width="100%">
 <tr>
   <th>Resource Name</th>
   <th>Description</th>
 </tr>
 <tr>
   <td><a href="URL HERE">String</a></td>
   <td>RESOURCE DESCRIPTION</td>
 </tr>
</table>

### JavaSCript
<table width="100%">
 <tr>
   <th>Resource Name</th>
   <th>Description</th>
 </tr>
 <tr>
   <td><a href="URL HERE">String</a></td>
   <td>RESOURCE DESCRIPTION</td>
 </tr>
</table>

2024-06-09 02:54 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +   -[Javascript](#javascript)
```suggestion
   -[C++](#c)<br>
   -[Java](#java)<br>
   -[Python](#python)<br>
   -[Javascript](#javascript)<br>
```

2024-06-09 04:27 UTC, Pujan-sarkar commented
@jfmartinz sir check now , I think this is good , so please merge it.

2024-06-09 11:57 UTC, jfmartinz commented
Follow the format. Each table should have only 2 cols, Resource Name and Description.

2024-06-09 11:59 UTC, jfmartinz requested changes

2024-06-09 11:59 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +- [DSA implementation](#dsa-implementation-of-several-programming-languages)
```suggestion
- [DSA by language](#dsa-by-language)
```

2024-06-09 11:59 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +| **GitHub Repository**  | [The Algorithms - JavaScript](https://github.com/TheAlgorithms/Javascript)                        | A collection of DSA implementations in JavaScript.               |
Follow this format:
### Section name
<table width="100%">
 <tr>
   <th>Resource Name</th>
   <th>Description</th>
 </tr>
 <tr>
   <td><a href="URL HERE">RESOURCE NAME</a></td>
   <td>RESOURCE DESCRIPTION</td>
 </tr>
</table>

2024-06-09 11:59 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +   -[Javascript](#javascript)<br>
```suggestion
   - [C++](#c)<br>
   - [Java](#java)<br>
   - [Python](#python)<br>
   - [Javascript](#javascript)<br>
```

2024-06-09 15:45 UTC, Pujan-sarkar commented
@jfmartinz I guess now mall the changes has done ✌️

2024-06-10 05:36 UTC, jfmartinz requested changes
Change it:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/f11e2cb2-24f3-4317-9c56-f20ac580500d)

add space before the '-'. Like this
- C++
-  JS

2. Change the [heading](https://github.com/jfmartinz/ResourceHub/blob/549808fc8d21f3ae9ff74ec7da31c3fd5dc93e0e/Data%20Structures%20and%20Algorithm%20(DSA)/readme.md#dsa-implementation-of-several-programming-languages) to DSA by language

3. Remove the roadmap col in C++, Java, Python, JS
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/15474581-52e5-4abe-aacc-afb646a682f3)


4. I already provided the template for addign new table and still not following it.

Check the format of your table, is your table same thing with this format:

```markdown
### Section name
<table width="100%">
 <tr>
   <th>Resource Name</th>
   <th>Description</th>
 </tr>
 <tr>
   <td><a href="URL HERE">RESOURCE NAME</a></td>
   <td>RESOURCE DESCRIPTION</td>
 </tr>
</table>
```

5. Remove these lines between the tables:
![image](https://github.com/jfmartinz/ResourceHub/assets/129386460/e4fdde41-0403-4384-b5a4-06fe977e799f)

2024-06-11 17:49 UTC, Pujan-sarkar commented
@jfmartinz  If this is not working then unassign me i will work on any other issue

2024-06-13 06:20 UTC, jfmartinz approved these changes
LGTML!

2024-06-13 06:20 UTC, merged