added algorithms by languages section
jfmartinz/ResourceHub pull request #958
Opened 2024-06-08 06:59 UTC by ImmidiSivani

## Description
added algorithms for 3 languages in DSA .

Closes #759 

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

## Additional

2024-06-08 09:21 UTC, jfmartinz requested changes

2024-06-08 09:21 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +
```suggestion
Add a description here
```

2024-06-08 09:21 UTC, jfmartinz commented on Data Structures and Algorithm (DSA)/readme.md
> +</table>
You forgot to add a description in each resource. Check this [link](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md#how-to-add-a-resource)

2024-06-09 02:47 UTC, jfmartinz requested changes
Each language should have its own table like this:

### JavaScript
### Section name
<table width="100%">
 <tr>
   <th>Resource Name</th>
   <th>Description</th>
 </tr>
 <tr>
   <td><a href="URL HERE">RESOURCE NAME</a></td>
   <td>RESOURCE DESCRIPTION</td>
 </tr>
</table>

Java
### Section name
<table width="100%">
 <tr>
   <th>Resource Name</th>
   <th>Description</th>
 </tr>
 <tr>
   <td><a href="URL HERE">RESOURCE NAME</a></td>
   <td>RESOURCE DESCRIPTION</td>
 </tr>
</table>

I hope this is clear

2024-06-15 05:55 UTC, jfmartinz commented
You just need to add '>' before the description, why did  you close? After that change I can merged it

2024-06-15 07:23 UTC, ImmidiSivani commented
This branch has conflicts shall I create new branch and open new PR for review,if it is okay I will close it.

2024-06-16 02:49 UTC, jfmartinz commented
You can fix it if you want [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line)

2024-06-22 16:28 UTC, closed without merging