Game Development Resources Added
jfmartinz/ResourceHub pull request #980
Opened 2024-06-08 17:30 UTC by shuvadeepmondal

# Pull Request
- ` Game Development Resources `

## Description
 I have added the "Game Development" resources . There are some contents about the Roadmaps, Tools, Techniques , Books, 
 YouTube Channels & GitHub repository at the Resource page.

Closes #888  

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2024-06-09 02:35 UTC, jfmartinz requested changes

2024-06-09 02:35 UTC, jfmartinz commented on Game Development/readme.md
> +| [Game Development Roadmap](https://roadmap.sh/game) | Start your game development journey with roadmap.sh's guide. This comprehensive resource covers basic to advanced topics, including game design
Follow the format

2024-06-09 02:35 UTC, jfmartinz commented on Game Development/readme.md
> +| [freeCodeCamp - Game Development](https://www.freecodecamp.org/news/tag/game-development/) | Provides free tutorials and articles on game development concepts and techniques. | Free |
Follow the format

2024-06-09 02:35 UTC, jfmartinz commented on Game Development/readme.md
> +| [Unity Tech Demos](https://github.com/Unity-Technologies/UnityCsReference) | Unity Technologies' repository of tech demos and sample projects. |
Follow the format

2024-06-09 03:15 UTC, shuvadeepmondal commented on Game Development/readme.md
> +| [Unity Tech Demos](https://github.com/Unity-Technologies/UnityCsReference) | Unity Technologies' repository of tech demos and sample projects. |
Okay Sir

2024-06-09 04:14 UTC, shuvadeepmondal commented
@jfmartinz Sir i have done the changes

2024-06-10 05:24 UTC, jfmartinz approved these changes

2024-06-10 05:25 UTC, merged